apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: di288nk7x-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: di288nk7x-python 
  name: di288nk7x-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: di288nk7x-python 
